# Generated by Django 2.2.6 on 2019-11-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '命令',
                'verbose_name_plural': '命令',
                'db_table': 'command',
            },
        ),
        migrations.CreateModel(
            name='GroupName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': '组名',
                'verbose_name_plural': '组名',
                'db_table': 'group_name',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time', models.DateTimeField(auto_created=True)),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('role_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_main.Role')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('state', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_main.User')),
            ],
            options={
                'verbose_name': '用户任务列表',
                'verbose_name_plural': '用户任务列表',
                'db_table': 'user_task',
            },
        ),
        migrations.CreateModel(
            name='UserTaskCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_main.UserTask')),
            ],
            options={
                'verbose_name': '执行清单命令',
                'verbose_name_plural': '执行清单命令',
                'db_table': 'user_task_command',
            },
        ),
        migrations.CreateModel(
            name='UserTaskCommandArgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(max_length=100)),
                ('arg_name', models.CharField(max_length=100)),
                ('command_data', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user_command_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_main.UserTaskCommand')),
            ],
            options={
                'verbose_name': '执行清单命令参数',
                'verbose_name_plural': '执行清单命令参数',
                'db_table': 'user_task_command_args',
            },
        ),
        migrations.CreateModel(
            name='RoleCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_main.Command')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_main.Role')),
            ],
            options={
                'verbose_name': '角色命令权限',
                'verbose_name_plural': '角色命令权限',
                'db_table': 'role_command',
            },
        ),
        migrations.CreateModel(
            name='GroupIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('login_ip', models.CharField(max_length=30)),
                ('login_user', models.CharField(max_length=30)),
                ('login_port', models.CharField(max_length=30)),
                ('login_password', models.CharField(max_length=100)),
                ('connect', models.CharField(max_length=100)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_main.GroupName')),
            ],
            options={
                'verbose_name': 'IP',
                'verbose_name_plural': 'IP',
                'db_table': 'group_ip',
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('STATE', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=0)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_main.UserTask')),
            ],
            options={
                'verbose_name': '用户执行日志',
                'verbose_name_plural': '用户执行日志',
                'db_table': 'event_log',
            },
        ),
        migrations.CreateModel(
            name='CommandArgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('command_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_main.Command')),
            ],
            options={
                'verbose_name': '命令参数',
                'verbose_name_plural': '命令参数',
                'db_table': 'command_args',
            },
        ),
    ]
