# Generated by Django 2.2.6 on 2019-11-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandargs',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
