# Generated by Django 2.2.6 on 2019-11-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_main', '0002_auto_20191104_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='task_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
