# Generated by Django 2.2.6 on 2019-11-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_main', '0005_auto_20191104_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskcommand',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_main.UserTask'),
        ),
    ]
