# Generated by Django 2.2.6 on 2019-11-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_main', '0006_auto_20191104_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='details_log',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
