# Generated by Django 2.2.6 on 2019-11-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_main', '0007_eventlog_details_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskcommand',
            name='command_task_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
