# Generated by Django 2.2.6 on 2019-11-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_main', '0008_usertaskcommand_command_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='group_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
