# Generated by Django 3.0 on 2019-12-31 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_main', '0009_usertask_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='group_id',
        ),
        migrations.CreateModel(
            name='ExecTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100)),
                ('status', models.CharField(default=0, max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansible_main.UserTask')),
            ],
            options={
                'verbose_name': '任务执行表',
                'verbose_name_plural': '任务执行表',
                'db_table': 'exec_task',
            },
        ),
    ]
